-- Supabase PostgreSQL schema for the Student Payment & Material Hub.
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.settings (
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value text not null,
  primary key (user_id, key)
);

create table if not exists public.students (
  student_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  roll_no text not null,
  student_name text not null,
  required_amount numeric(12,2) not null default 0,
  unique (user_id, roll_no)
);

create table if not exists public.payments (
  payment_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint not null references public.students(student_id) on delete cascade,
  amount_paid numeric(12,2) not null check (amount_paid > 0),
  payment_mode text not null check (payment_mode in ('UPI','Cash')),
  transaction_details text,
  payment_date date not null
);

create table if not exists public.materials (
  material_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint not null references public.students(student_id) on delete cascade,
  material_name text not null,
  received_status text not null check (received_status in ('Received','Not Received')),
  received_date date,
  unique (user_id, student_id, material_name)
);

-- Row Level Security is enabled as an additional protection.
-- The Flask server uses the Supabase service role only on the server and
-- still scopes every query by the authenticated user's UUID.
alter table public.settings enable row level security;
alter table public.students enable row level security;
alter table public.payments enable row level security;
alter table public.materials enable row level security;

drop policy if exists "Users manage their own settings" on public.settings;
create policy "Users manage their own settings" on public.settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their own students" on public.students;
create policy "Users manage their own students" on public.students
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their own payments" on public.payments;
create policy "Users manage their own payments" on public.payments
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage their own materials" on public.materials;
create policy "Users manage their own materials" on public.materials
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists students_user_id_idx on public.students(user_id);
create index if not exists payments_user_id_student_id_idx on public.payments(user_id, student_id);
create index if not exists materials_user_id_student_id_idx on public.materials(user_id, student_id);
